# Generated by Django 4.0.6 on 2022-07-05 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=14)),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('cnpj', models.CharField(max_length=14, null=True)),
                ('tipo', models.CharField(choices=[('PF', 'Fisica'), ('PJ', 'Juridica')], default='PF', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('km', models.FloatField()),
                ('carga', models.FloatField()),
                ('bagageiro', models.IntegerField()),
                ('portas', models.IntegerField()),
                ('tipo', models.CharField(choices=[('VL', 'Automovel'), ('VP', 'Caminhao')], default='VL', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateField()),
                ('data_devolucao', models.DateField()),
                ('km_rodado', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluguel_veiculos.cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluguel_veiculos.veiculo')),
            ],
            options={
                'verbose_name_plural': 'Alugueis',
            },
        ),
    ]
