# Generated by Django 4.0.6 on 2022-07-12 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel_veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='valor',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='data_devolucao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='data_retirada',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
