# Generated by Django 4.0.6 on 2022-07-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel_veiculos', '0002_aluguel_valor_alter_aluguel_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='valor',
            field=models.FloatField(null=True),
        ),
    ]
