# Generated by Django 4.0.5 on 2022-07-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel_veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluguel',
            options={'verbose_name_plural': 'Alugueis'},
        ),
    ]
